# Generated by Django 6.1.1 on 2026-10-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
