# Generated by Django 6.1.1 on 2026-10-04 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0002_document_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('chunk_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_chunks', to='investigator.document')),
            ],
        ),
    ]
