# Generated by Django 6.1.1 on 2026-10-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator', '0003_evidencechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencechunk',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencechunk',
            name='section_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evidencechunk',
            name='source_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
